library(tidyverse)
library(ggpubr)
data0010 = read.table(file = "results0010.txt")
data0010$noloci <- as.factor(data0010$noloci)
data0011 = read.table(file = "results0011.txt")
data0011$noloci <- as.factor(data0011$noloci)


p1=ggplot(data = data0010, aes(x=ID, y=theta_1A, color = noloci)) + labs(title=bquote(~theta[A]~"(Model A)")) + geom_point() + geom_errorbar(data = data0010, width=0.4, mapping=aes(x=ID, ymax=theta_1A_UCI, ymin=theta_1A_LCI)) + geom_hline(aes(yintercept=0.001)) + scale_y_continuous(limits = c(0,0.008)) + theme( panel.background = element_rect(fill = "white", colour = "black", size = 0.5, linetype = "solid"), panel.grid.major = element_line(size = 0.5, linetype = 'solid', colour = "grey"), panel.grid.major.x = element_blank(), panel.grid.minor = element_blank(), axis.title.x = element_blank(), axis.title.y = element_blank(), axis.text.x = element_blank(), axis.ticks.x=element_blank(), legend.position="none", plot.title = element_text(hjust = 0.5), strip.background = element_blank(), strip.text.x = element_blank()) + facet_wrap(~noloci,scales="free_x",ncol=3)

p2=ggplot(data = data0010, aes(x=ID, y=theta_3C, color = noloci)) + labs(title=bquote(~theta[C]~"(Model A)")) + geom_point() + geom_errorbar(data = data0010, width=0.4, mapping=aes(x=ID, ymax=theta_3C_UCI, ymin=theta_3C_LCI)) + geom_hline(aes(yintercept=0.001)) + scale_y_continuous(limits = c(0,0.008)) + theme( panel.background = element_rect(fill = "white", colour = "black", size = 0.5, linetype = "solid"), panel.grid.major = element_line(size = 0.5, linetype = 'solid', colour = "grey"), panel.grid.major.x = element_blank(), panel.grid.minor = element_blank(), axis.title.x = element_blank(), axis.title.y = element_blank(), axis.text.x = element_blank(), axis.ticks.x=element_blank(), legend.position="none", plot.title = element_text(hjust = 0.5), strip.background = element_blank(), strip.text.x = element_blank()) + facet_wrap(~noloci,scales="free_x",ncol=3)

p3=ggplot(data = data0010, aes(x=ID, y=theta_4R, color = noloci)) + labs(title=bquote(~theta[R]~"(Model A)")) + geom_point() + geom_errorbar(data = data0010, width=0.4, mapping=aes(x=ID, ymax=theta_4R_UCI, ymin=theta_4R_LCI)) + geom_hline(aes(yintercept=0.001)) + scale_y_continuous(limits = c(0,0.008)) + theme( panel.background = element_rect(fill = "white", colour = "black", size = 0.5, linetype = "solid"), panel.grid.major = element_line(size = 0.5, linetype = 'solid', colour = "grey"), panel.grid.major.x = element_blank(), panel.grid.minor = element_blank(), axis.title.x = element_blank(), axis.title.y = element_blank(), axis.text.x = element_blank(), axis.ticks.x=element_blank(), legend.position="none", plot.title = element_text(hjust = 0.5), strip.background = element_blank(), strip.text.x = element_blank()) + facet_wrap(~noloci,scales="free_x",ncol=3)

p4=ggplot(data = data0010, aes(x=ID, y=theta_5S, color = noloci)) + labs(title=bquote(~theta[S]~"(Model A)")) + geom_point() + geom_errorbar(data = data0010, width=0.4, mapping=aes(x=ID, ymax=theta_5S_UCI, ymin=theta_5S_LCI)) + geom_hline(aes(yintercept=0.001)) + scale_y_continuous(limits = c(0,0.008)) + theme( panel.background = element_rect(fill = "white", colour = "black", size = 0.5, linetype = "solid"), panel.grid.major = element_line(size = 0.5, linetype = 'solid', colour = "grey"), panel.grid.major.x = element_blank(), panel.grid.minor = element_blank(), axis.title.x = element_blank(), axis.title.y = element_blank(), axis.text.x = element_blank(), axis.ticks.x=element_blank(), legend.position="none", plot.title = element_text(hjust = 0.5), strip.background = element_blank(), strip.text.x = element_blank()) + facet_wrap(~noloci,scales="free_x",ncol=3)

p5=ggplot(data = data0010, aes(x=ID, y=theta_6H, color = noloci)) + labs(title=bquote(~theta[H]~"(Model A)")) + geom_point() + geom_errorbar(data = data0010, width=0.4, mapping=aes(x=ID, ymax=theta_6H_UCI, ymin=theta_6H_LCI)) + geom_hline(aes(yintercept=0.001)) + scale_y_continuous(limits = c(0,0.008)) + theme( panel.background = element_rect(fill = "white", colour = "black", size = 0.5, linetype = "solid"), panel.grid.major = element_line(size = 0.5, linetype = 'solid', colour = "grey"), panel.grid.major.x = element_blank(), panel.grid.minor = element_blank(), axis.title.x = element_blank(), axis.title.y = element_blank(), axis.text.x = element_blank(), axis.ticks.x=element_blank(), legend.position="none", plot.title = element_text(hjust = 0.5), strip.background = element_blank(), strip.text.x = element_blank()) + facet_wrap(~noloci,scales="free_x",ncol=3)

p6=ggplot(data = data0010, aes(x=ID, y=phi_H, color = noloci)) + labs(title = bquote(~phi~" (Model A)")) + geom_point() + geom_errorbar(data = data0010, width=0.4, mapping=aes(x=ID, ymax=phi_H_UCI, ymin=phi_H_LCI)) + geom_hline(aes(yintercept=0.1))  + scale_y_continuous(limits = c(0,1.0)) + theme( panel.background = element_rect(fill = "white", colour = "black", size = 0.5, linetype = "solid"), panel.grid.major = element_line(size = 0.5, linetype = 'solid', colour = "grey"), panel.grid.major.x = element_blank(), panel.grid.minor = element_blank(), axis.title.x = element_blank(), axis.title.y = element_blank(), axis.text.x = element_blank(), axis.ticks.x=element_blank(), legend.position="none", plot.title = element_text(hjust = 0.5), strip.background = element_blank(), strip.text.x = element_blank()) + facet_wrap(~noloci,scales="free_x",ncol=3)

p7=ggplot(data = data0010, aes(x=ID, y=tau_4R, color = noloci)) + labs(title = bquote(~tau[R]~" (Model A)")) + geom_point() + geom_errorbar(data = data0010, width=0.4, mapping=aes(x=ID, ymax=tau_4R_UCI, ymin=tau_4R_LCI)) + geom_hline(aes(yintercept=0.03)) + scale_y_continuous(limits = c(0,0.05)) + theme( panel.background = element_rect(fill = "white", colour = "black", size = 0.5, linetype = "solid"), panel.grid.major = element_line(size = 0.5, linetype = 'solid', colour = "grey"), panel.grid.major.x = element_blank(), panel.grid.minor = element_blank(), axis.title.x = element_blank(), axis.title.y = element_blank(), axis.text.x = element_blank(), axis.ticks.x=element_blank(), legend.position="none", plot.title = element_text(hjust = 0.5), strip.background = element_blank(), strip.text.x = element_blank()) + facet_wrap(~noloci,scales="free_x",ncol=3)

p8=ggplot(data = data0010, aes(x=ID, y=tau_5S, color = noloci)) + labs(title = bquote(~tau[S]~" (Model A)")) + geom_point() + geom_errorbar(data = data0010, width=0.4, mapping=aes(x=ID, ymax=tau_5S_UCI, ymin=tau_5S_LCI)) + geom_hline(aes(yintercept=0.02)) + scale_y_continuous(limits = c(0,0.05)) + theme( panel.background = element_rect(fill = "white", colour = "black", size = 0.5, linetype = "solid"), panel.grid.major = element_line(size = 0.5, linetype = 'solid', colour = "grey"), panel.grid.major.x = element_blank(), panel.grid.minor = element_blank(), axis.title.x = element_blank(), axis.title.y = element_blank(), axis.text.x = element_blank(), axis.ticks.x=element_blank(), legend.position="none", plot.title = element_text(hjust = 0.5), strip.background = element_blank(), strip.text.x = element_blank()) + facet_wrap(~noloci,scales="free_x",ncol=3)

p9=ggplot(data = data0010, aes(x=ID, y=tau_6H, color = noloci)) + labs(title = bquote(~tau[H]~" (Model A)")) + geom_point() + geom_errorbar(data = data0010, width=0.4, mapping=aes(x=ID, ymax=tau_6H_UCI, ymin=tau_6H_LCI)) + geom_hline(aes(yintercept=0.01)) + scale_y_continuous(limits = c(0,0.05)) + theme( panel.background = element_rect(fill = "white", colour = "black", size = 0.5, linetype = "solid"), panel.grid.major = element_line(size = 0.5, linetype = 'solid', colour = "grey"), panel.grid.major.x = element_blank(), panel.grid.minor = element_blank(), axis.title.x = element_blank(), axis.title.y = element_blank(), axis.text.x = element_blank(), axis.ticks.x=element_blank(), legend.position="none", plot.title = element_text(hjust = 0.5), strip.background = element_blank(), strip.text.x = element_blank()) + facet_wrap(~noloci,scales="free_x",ncol=3)

p10=ggplot(data = data0011, aes(x=ID, y=theta_1A, color = noloci)) + labs(title=bquote(~theta[A]~"(Model C)")) + geom_point() + geom_errorbar(data = data0011, width=0.4, mapping=aes(x=ID, ymax=theta_1A_UCI, ymin=theta_1A_LCI)) + geom_hline(aes(yintercept=0.001)) + scale_y_continuous(limits = c(0,0.008)) + theme( panel.background = element_rect(fill = "white", colour = "black", size = 0.5, linetype = "solid"), panel.grid.major = element_line(size = 0.5, linetype = 'solid', colour = "grey"), panel.grid.major.x = element_blank(), panel.grid.minor = element_blank(), axis.title.x = element_blank(), axis.title.y = element_blank(), axis.text.x = element_blank(), axis.ticks.x=element_blank(), legend.position="none", plot.title = element_text(hjust = 0.5), strip.background = element_blank(), strip.text.x = element_blank()) + facet_wrap(~noloci,scales="free_x",ncol=3)

p11=ggplot(data = data0011, aes(x=ID, y=theta_3C, color = noloci)) + labs(title=bquote(~theta[C]~"(Model C)")) + geom_point() + geom_errorbar(data = data0011, width=0.4, mapping=aes(x=ID, ymax=theta_3C_UCI, ymin=theta_3C_LCI)) + geom_hline(aes(yintercept=0.001)) + scale_y_continuous(limits = c(0,0.008)) + theme( panel.background = element_rect(fill = "white", colour = "black", size = 0.5, linetype = "solid"), panel.grid.major = element_line(size = 0.5, linetype = 'solid', colour = "grey"), panel.grid.major.x = element_blank(), panel.grid.minor = element_blank(), axis.title.x = element_blank(), axis.title.y = element_blank(), axis.text.x = element_blank(), axis.ticks.x=element_blank(), legend.position="none", plot.title = element_text(hjust = 0.5), strip.background = element_blank(), strip.text.x = element_blank()) + facet_wrap(~noloci,scales="free_x",ncol=3)

p12=ggplot(data = data0011, aes(x=ID, y=theta_4R, color = noloci)) + labs(title=bquote(~theta[R]~"(Model C)")) + geom_point() + geom_errorbar(data = data0011, width=0.4, mapping=aes(x=ID, ymax=theta_4R_UCI, ymin=theta_4R_LCI)) + geom_hline(aes(yintercept=0.001)) + scale_y_continuous(limits = c(0,0.008)) + theme( panel.background = element_rect(fill = "white", colour = "black", size = 0.5, linetype = "solid"), panel.grid.major = element_line(size = 0.5, linetype = 'solid', colour = "grey"), panel.grid.major.x = element_blank(), panel.grid.minor = element_blank(), axis.title.x = element_blank(), axis.title.y = element_blank(), axis.text.x = element_blank(), axis.ticks.x=element_blank(), legend.position="none", plot.title = element_text(hjust = 0.5), strip.background = element_blank(), strip.text.x = element_blank()) + facet_wrap(~noloci,scales="free_x",ncol=3)

p13=ggplot(data = data0011, aes(x=ID, y=theta_5S, color = noloci)) + labs(title=bquote(~theta[S]~"(Model C)")) + geom_point() + geom_errorbar(data = data0011, width=0.4, mapping=aes(x=ID, ymax=theta_5S_UCI, ymin=theta_5S_LCI)) + geom_hline(aes(yintercept=0.001)) + scale_y_continuous(limits = c(0,0.008)) + theme( panel.background = element_rect(fill = "white", colour = "black", size = 0.5, linetype = "solid"), panel.grid.major = element_line(size = 0.5, linetype = 'solid', colour = "grey"), panel.grid.major.x = element_blank(), panel.grid.minor = element_blank(), axis.title.x = element_blank(), axis.title.y = element_blank(), axis.text.x = element_blank(), axis.ticks.x=element_blank(), legend.position="none", plot.title = element_text(hjust = 0.5)) + facet_wrap(~noloci,scales="free_x",ncol=3,strip.position = "bottom")

p14=ggplot(data = data0011, aes(x=ID, y=phi_H, color = noloci)) + labs(title = bquote(~phi~" (Model C)")) + geom_point() + geom_errorbar(data = data0011, width=0.4, mapping=aes(x=ID, ymax=phi_H_UCI, ymin=phi_H_LCI)) + geom_hline(aes(yintercept=0.1))  + scale_y_continuous(limits = c(0,1.0)) + theme( panel.background = element_rect(fill = "white", colour = "black", size = 0.5, linetype = "solid"), panel.grid.major = element_line(size = 0.5, linetype = 'solid', colour = "grey"), panel.grid.major.x = element_blank(), panel.grid.minor = element_blank(), axis.title.x = element_blank(), axis.title.y = element_blank(), axis.text.x = element_blank(), axis.ticks.x=element_blank(), legend.position="none", plot.title = element_text(hjust = 0.5)) + facet_wrap(~noloci,scales="free_x",ncol=3,strip.position = "bottom")

p15=ggplot(data = data0011, aes(x=ID, y=tau_4R, color = noloci)) + labs(title=bquote(~tau[R]~"(Model C)")) + geom_point() + geom_errorbar(data = data0011, width=0.4, mapping=aes(x=ID, ymax=tau_4R_UCI, ymin=tau_4R_LCI)) + geom_hline(aes(yintercept=0.03)) + scale_y_continuous(limits = c(0,0.05)) + theme( panel.background = element_rect(fill = "white", colour = "black", size = 0.5, linetype = "solid"), panel.grid.major = element_line(size = 0.5, linetype = 'solid', colour = "grey"), panel.grid.major.x = element_blank(), panel.grid.minor = element_blank(), axis.title.x = element_blank(), axis.title.y = element_blank(), axis.text.x = element_blank(), axis.ticks.x=element_blank(), legend.position="none", plot.title = element_text(hjust = 0.5)) + facet_wrap(~noloci,scales="free_x",ncol=3,strip.position = "bottom")

p16=ggplot(data = data0011, aes(x=ID, y=tau_6H, color = noloci)) + labs(title=bquote(~tau[H]~"(Model C)")) + geom_point() + geom_errorbar(data = data0011, width=0.4, mapping=aes(x=ID, ymax=tau_6H_UCI, ymin=tau_6H_LCI)) + geom_hline(aes(yintercept=0.01)) + scale_y_continuous(limits = c(0,0.05)) + theme( panel.background = element_rect(fill = "white", colour = "black", size = 0.5, linetype = "solid"), panel.grid.major = element_line(size = 0.5, linetype = 'solid', colour = "grey"), panel.grid.major.x = element_blank(), panel.grid.minor = element_blank(), axis.title.x = element_blank(), axis.title.y = element_blank(), axis.text.x = element_blank(), axis.ticks.x=element_blank(), legend.position="none", plot.title = element_text(hjust = 0.5)) + facet_wrap(~noloci,scales="free_x",ncol=3,strip.position = "bottom")


fig1=ggarrange(p1,p2,p3,p4,p5,p6,p7,p8,p9,p10,p11,p12,p13,p14,p15,p16,ncol=4,nrow=4)
annotate_figure(fig1, top = text_grob("BPP Posterior Mean and 95% HPD Credible Set for Simulated Data (\u03b8 = 0.001, \u03c6 = 0.10, GTR+\u0393)", color = "black", face = "bold", size = 14))

ggsave(filename="figure001.pdf",width=11,height=8.5,device=cairo_pdf)
