library(tidyverse)
library(ggpubr)
data0100 = read.table(file = "results0100.txt")
data0100$noloci <- as.factor(data0100$noloci)
data0101 = read.table(file = "results0101.txt")
data0101$noloci <- as.factor(data0101$noloci)


p1=ggplot(data = data0100, aes(x=ID, y=theta_1A, color = noloci)) + ggtitle("Posterior \u03b8 for A (Model A)") + geom_point() + geom_errorbar(data = data0100, width=0.4, mapping=aes(x=ID, ymax=theta_1A_UCI, ymin=theta_1A_LCI)) + geom_hline(aes(yintercept=0.01)) + scale_y_continuous(limits = c(0,0.05)) + theme( panel.background = element_rect(fill = "white", colour = "black", size = 0.5, linetype = "solid"), panel.grid.major = element_line(size = 0.5, linetype = 'solid', colour = "grey"), panel.grid.major.x = element_blank(), panel.grid.minor = element_blank(), axis.title.x = element_blank(), axis.title.y = element_blank(), axis.text.x = element_blank(), axis.ticks.x=element_blank(), legend.position="none", plot.title = element_text(hjust = 0.5)) + facet_wrap(~noloci,scales="free_x",ncol=3)

p2=ggplot(data = data0100, aes(x=ID, y=theta_3C, color = noloci)) + ggtitle("Posterior \u03b8 for C (Model A)") + geom_point() + geom_errorbar(data = data0100, width=0.4, mapping=aes(x=ID, ymax=theta_3C_UCI, ymin=theta_3C_LCI)) + geom_hline(aes(yintercept=0.01)) + scale_y_continuous(limits = c(0,0.05)) + theme( panel.background = element_rect(fill = "white", colour = "black", size = 0.5, linetype = "solid"), panel.grid.major = element_line(size = 0.5, linetype = 'solid', colour = "grey"), panel.grid.major.x = element_blank(), panel.grid.minor = element_blank(), axis.title.x = element_blank(), axis.title.y = element_blank(), axis.text.x = element_blank(), axis.ticks.x=element_blank(), legend.position="none", plot.title = element_text(hjust = 0.5)) + facet_wrap(~noloci,scales="free_x",ncol=3)

p3=ggplot(data = data0100, aes(x=ID, y=theta_4R, color = noloci)) + ggtitle("Posterior \u03b8 for R (Model A)") + geom_point() + geom_errorbar(data = data0100, width=0.4, mapping=aes(x=ID, ymax=theta_4R_UCI, ymin=theta_4R_LCI)) + geom_hline(aes(yintercept=0.01)) + scale_y_continuous(limits = c(0,0.05)) + theme( panel.background = element_rect(fill = "white", colour = "black", size = 0.5, linetype = "solid"), panel.grid.major = element_line(size = 0.5, linetype = 'solid', colour = "grey"), panel.grid.major.x = element_blank(), panel.grid.minor = element_blank(), axis.title.x = element_blank(), axis.title.y = element_blank(), axis.text.x = element_blank(), axis.ticks.x=element_blank(), legend.position="none", plot.title = element_text(hjust = 0.5)) + facet_wrap(~noloci,scales="free_x",ncol=3)

p4=ggplot(data = data0100, aes(x=ID, y=theta_5S, color = noloci)) + ggtitle("Posterior \u03b8 for S (Model A)") + geom_point() + geom_errorbar(data = data0100, width=0.4, mapping=aes(x=ID, ymax=theta_5S_UCI, ymin=theta_5S_LCI)) + geom_hline(aes(yintercept=0.01)) + scale_y_continuous(limits = c(0,0.05)) + theme( panel.background = element_rect(fill = "white", colour = "black", size = 0.5, linetype = "solid"), panel.grid.major = element_line(size = 0.5, linetype = 'solid', colour = "grey"), panel.grid.major.x = element_blank(), panel.grid.minor = element_blank(), axis.title.x = element_blank(), axis.title.y = element_blank(), axis.text.x = element_blank(), axis.ticks.x=element_blank(), legend.position="none", plot.title = element_text(hjust = 0.5)) + facet_wrap(~noloci,scales="free_x",ncol=3)

p5=ggplot(data = data0100, aes(x=ID, y=theta_6H, color = noloci)) + ggtitle("Posterior \u03b8 for H (Model A)") + geom_point() + geom_errorbar(data = data0100, width=0.4, mapping=aes(x=ID, ymax=theta_6H_UCI, ymin=theta_6H_LCI)) + geom_hline(aes(yintercept=0.01)) + scale_y_continuous(limits = c(0,0.05)) + theme( panel.background = element_rect(fill = "white", colour = "black", size = 0.5, linetype = "solid"), panel.grid.major = element_line(size = 0.5, linetype = 'solid', colour = "grey"), panel.grid.major.x = element_blank(), panel.grid.minor = element_blank(), axis.title.x = element_blank(), axis.title.y = element_blank(), axis.text.x = element_blank(), axis.ticks.x=element_blank(), legend.position="none", plot.title = element_text(hjust = 0.5)) + facet_wrap(~noloci,scales="free_x",ncol=3)

p6=ggplot(data = data0100, aes(x=ID, y=phi_H, color = noloci)) + ggtitle("Posterior \u03c6 (Model A)") + geom_point() + geom_errorbar(data = data0100, width=0.4, mapping=aes(x=ID, ymax=phi_H_UCI, ymin=phi_H_LCI)) + geom_hline(aes(yintercept=0.1))  + scale_y_continuous(limits = c(0,1.0)) + theme( panel.background = element_rect(fill = "white", colour = "black", size = 0.5, linetype = "solid"), panel.grid.major = element_line(size = 0.5, linetype = 'solid', colour = "grey"), panel.grid.major.x = element_blank(), panel.grid.minor = element_blank(), axis.title.x = element_blank(), axis.title.y = element_blank(), axis.text.x = element_blank(), axis.ticks.x=element_blank(), legend.position="none", plot.title = element_text(hjust = 0.5)) + facet_wrap(~noloci,scales="free_x",ncol=3)

p7=ggplot(data = data0100, aes(x=ID, y=tau_4R, color = noloci)) + ggtitle("Posterior \u03c4 for R (Model A)") + geom_point() + geom_errorbar(data = data0100, width=0.4, mapping=aes(x=ID, ymax=tau_4R_UCI, ymin=tau_4R_LCI)) + geom_hline(aes(yintercept=0.03)) + scale_y_continuous(limits = c(0,0.05)) + theme( panel.background = element_rect(fill = "white", colour = "black", size = 0.5, linetype = "solid"), panel.grid.major = element_line(size = 0.5, linetype = 'solid', colour = "grey"), panel.grid.major.x = element_blank(), panel.grid.minor = element_blank(), axis.title.x = element_blank(), axis.title.y = element_blank(), axis.text.x = element_blank(), axis.ticks.x=element_blank(), legend.position="none", plot.title = element_text(hjust = 0.5)) + facet_wrap(~noloci,scales="free_x",ncol=3)

p8=ggplot(data = data0100, aes(x=ID, y=tau_5S, color = noloci)) + ggtitle("Posterior \u03c4 for S (Model A)") + geom_point() + geom_errorbar(data = data0100, width=0.4, mapping=aes(x=ID, ymax=tau_5S_UCI, ymin=tau_5S_LCI)) + geom_hline(aes(yintercept=0.02)) + scale_y_continuous(limits = c(0,0.05)) + theme( panel.background = element_rect(fill = "white", colour = "black", size = 0.5, linetype = "solid"), panel.grid.major = element_line(size = 0.5, linetype = 'solid', colour = "grey"), panel.grid.major.x = element_blank(), panel.grid.minor = element_blank(), axis.title.x = element_blank(), axis.title.y = element_blank(), axis.text.x = element_blank(), axis.ticks.x=element_blank(), legend.position="none", plot.title = element_text(hjust = 0.5)) + facet_wrap(~noloci,scales="free_x",ncol=3)

p9=ggplot(data = data0100, aes(x=ID, y=tau_6H, color = noloci)) + ggtitle("Posterior \u03c4 for H (Model A)") + geom_point() + geom_errorbar(data = data0100, width=0.4, mapping=aes(x=ID, ymax=tau_6H_UCI, ymin=tau_6H_LCI)) + geom_hline(aes(yintercept=0.01)) + scale_y_continuous(limits = c(0,0.05)) + theme( panel.background = element_rect(fill = "white", colour = "black", size = 0.5, linetype = "solid"), panel.grid.major = element_line(size = 0.5, linetype = 'solid', colour = "grey"), panel.grid.major.x = element_blank(), panel.grid.minor = element_blank(), axis.title.x = element_blank(), axis.title.y = element_blank(), axis.text.x = element_blank(), axis.ticks.x=element_blank(), legend.position="none", plot.title = element_text(hjust = 0.5)) + facet_wrap(~noloci,scales="free_x",ncol=3)

p10=ggplot(data = data0101, aes(x=ID, y=theta_1A, color = noloci)) + ggtitle("Posterior \u03b8 for A (Model C)") + geom_point() + geom_errorbar(data = data0101, width=0.4, mapping=aes(x=ID, ymax=theta_1A_UCI, ymin=theta_1A_LCI)) + geom_hline(aes(yintercept=0.01)) + scale_y_continuous(limits = c(0,0.05)) + theme( panel.background = element_rect(fill = "white", colour = "black", size = 0.5, linetype = "solid"), panel.grid.major = element_line(size = 0.5, linetype = 'solid', colour = "grey"), panel.grid.major.x = element_blank(), panel.grid.minor = element_blank(), axis.title.x = element_blank(), axis.title.y = element_blank(), axis.text.x = element_blank(), axis.ticks.x=element_blank(), legend.position="none", plot.title = element_text(hjust = 0.5)) + facet_wrap(~noloci,scales="free_x",ncol=3)

p11=ggplot(data = data0101, aes(x=ID, y=theta_3C, color = noloci)) + ggtitle("Posterior \u03b8 for C (Model C)") + geom_point() + geom_errorbar(data = data0101, width=0.4, mapping=aes(x=ID, ymax=theta_3C_UCI, ymin=theta_3C_LCI)) + geom_hline(aes(yintercept=0.01)) + scale_y_continuous(limits = c(0,0.05)) + theme( panel.background = element_rect(fill = "white", colour = "black", size = 0.5, linetype = "solid"), panel.grid.major = element_line(size = 0.5, linetype = 'solid', colour = "grey"), panel.grid.major.x = element_blank(), panel.grid.minor = element_blank(), axis.title.x = element_blank(), axis.title.y = element_blank(), axis.text.x = element_blank(), axis.ticks.x=element_blank(), legend.position="none", plot.title = element_text(hjust = 0.5)) + facet_wrap(~noloci,scales="free_x",ncol=3)

p12=ggplot(data = data0101, aes(x=ID, y=theta_4R, color = noloci)) + ggtitle("Posterior \u03b8 for R (Model C)") + geom_point() + geom_errorbar(data = data0101, width=0.4, mapping=aes(x=ID, ymax=theta_4R_UCI, ymin=theta_4R_LCI)) + geom_hline(aes(yintercept=0.01)) + scale_y_continuous(limits = c(0,0.05)) + theme( panel.background = element_rect(fill = "white", colour = "black", size = 0.5, linetype = "solid"), panel.grid.major = element_line(size = 0.5, linetype = 'solid', colour = "grey"), panel.grid.major.x = element_blank(), panel.grid.minor = element_blank(), axis.title.x = element_blank(), axis.title.y = element_blank(), axis.text.x = element_blank(), axis.ticks.x=element_blank(), legend.position="none", plot.title = element_text(hjust = 0.5)) + facet_wrap(~noloci,scales="free_x",ncol=3)

p13=ggplot(data = data0101, aes(x=ID, y=theta_5S, color = noloci)) + ggtitle("Posterior \u03b8 for S (Model C)") + geom_point() + geom_errorbar(data = data0101, width=0.4, mapping=aes(x=ID, ymax=theta_5S_UCI, ymin=theta_5S_LCI)) + geom_hline(aes(yintercept=0.01)) + scale_y_continuous(limits = c(0,0.05)) + theme( panel.background = element_rect(fill = "white", colour = "black", size = 0.5, linetype = "solid"), panel.grid.major = element_line(size = 0.5, linetype = 'solid', colour = "grey"), panel.grid.major.x = element_blank(), panel.grid.minor = element_blank(), axis.title.x = element_blank(), axis.title.y = element_blank(), axis.text.x = element_blank(), axis.ticks.x=element_blank(), legend.position="none", plot.title = element_text(hjust = 0.5)) + facet_wrap(~noloci,scales="free_x",ncol=3)

p14=ggplot(data = data0101, aes(x=ID, y=phi_H, color = noloci)) + ggtitle("Posterior \u03c6 (Model C)") + geom_point() + geom_errorbar(data = data0101, width=0.4, mapping=aes(x=ID, ymax=phi_H_UCI, ymin=phi_H_LCI)) + geom_hline(aes(yintercept=0.1))  + scale_y_continuous(limits = c(0,1.0)) + theme( panel.background = element_rect(fill = "white", colour = "black", size = 0.5, linetype = "solid"), panel.grid.major = element_line(size = 0.5, linetype = 'solid', colour = "grey"), panel.grid.major.x = element_blank(), panel.grid.minor = element_blank(), axis.title.x = element_blank(), axis.title.y = element_blank(), axis.text.x = element_blank(), axis.ticks.x=element_blank(), legend.position="none", plot.title = element_text(hjust = 0.5)) + facet_wrap(~noloci,scales="free_x",ncol=3)

p15=ggplot(data = data0101, aes(x=ID, y=tau_4R, color = noloci)) + ggtitle("Posterior \u03c4 for R (Model C)") + geom_point() + geom_errorbar(data = data0101, width=0.4, mapping=aes(x=ID, ymax=tau_4R_UCI, ymin=tau_4R_LCI)) + geom_hline(aes(yintercept=0.03)) + scale_y_continuous(limits = c(0,0.05)) + theme( panel.background = element_rect(fill = "white", colour = "black", size = 0.5, linetype = "solid"), panel.grid.major = element_line(size = 0.5, linetype = 'solid', colour = "grey"), panel.grid.major.x = element_blank(), panel.grid.minor = element_blank(), axis.title.x = element_blank(), axis.title.y = element_blank(), axis.text.x = element_blank(), axis.ticks.x=element_blank(), legend.position="none", plot.title = element_text(hjust = 0.5)) + facet_wrap(~noloci,scales="free_x",ncol=3)

p16=ggplot(data = data0101, aes(x=ID, y=tau_6H, color = noloci)) + ggtitle("Posterior \u03c4 for H (Model C)") + geom_point() + geom_errorbar(data = data0101, width=0.4, mapping=aes(x=ID, ymax=tau_6H_UCI, ymin=tau_6H_LCI)) + geom_hline(aes(yintercept=0.01)) + scale_y_continuous(limits = c(0,0.05)) + theme( panel.background = element_rect(fill = "white", colour = "black", size = 0.5, linetype = "solid"), panel.grid.major = element_line(size = 0.5, linetype = 'solid', colour = "grey"), panel.grid.major.x = element_blank(), panel.grid.minor = element_blank(), axis.title.x = element_blank(), axis.title.y = element_blank(), axis.text.x = element_blank(), axis.ticks.x=element_blank(), legend.position="none", plot.title = element_text(hjust = 0.5)) + facet_wrap(~noloci,scales="free_x",ncol=3)


fig1=ggarrange(p1,p2,p3,p4,p5,p6,p7,p8,p9,p10,p11,p12,p13,p14,p15,p16,ncol=4,nrow=4)
annotate_figure(fig1, top = text_grob("BPP Posterior Mean and 95% HPD Credible Set for Simulated Data (\u03b8 = 0.01, \u03c6 = 0.10, Model = Jukes-Cantor)", color = "black", face = "bold", size = 12))

ggsave(filename="figure010.pdf",width=11,height=8.5,device=cairo_pdf)
